version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
  - package_manager: "javascript"
    directory: "/example-electron-5"
    update_schedule: "live"
    ignored_updates:
      - match:
          dependency_name: "electron"
  - package_manager: "javascript"
    directory: "/example-electron-6"
    update_schedule: "live"
    ignored_updates:
      - match:
          dependency_name: "electron"
  - package_manager: "javascript"
    directory: "/example-electron-7"
    update_schedule: "live"
    ignored_updates:
      - match:
          dependency_name: "electron"
  - package_manager: "javascript"
    directory: "/example-electron-8"
    update_schedule: "live"
    ignored_updates:
      - match:
          dependency_name: "electron"
  - package_manager: "javascript"
    directory: "/example-electron-9"
    update_schedule: "live"
    ignored_updates:
      - match:
          dependency_name: "electron"
  - package_manager: "javascript"
    directory: "/library"
    update_schedule: "live"
